# -*- mode: dockerfile -*-

FROM python:3.7.2-alpine3.9

RUN apk add --no-cache --update \
  bash \
  ca-certificates

WORKDIR /app
COPY requirements.txt /app/

RUN apk add --no-cache --update --virtual .build-deps \
  g++ \
  && pip install --upgrade -r requirements.txt \
  && apk del .build-deps
